services:
  redis-db:
    image: redis:latest
    container_name: redis-db
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
    restart: always
    ports:
      - "${REDIS_PORT}:6379"

  weather-api-service:
    container_name: weather-api-service
    build: 
      context: .
      dockerfile: Dockerfile.weather-api
    environment:
      - SERVICE_NAME=weather-api
      - API_HOST=${API_HOST}
      - API_PORT=${API_PORT}
      - REDIS_HOST=redis-db
      - REDIS_PORT=${REDIS_PORT}
    ports:
      - "${API_PORT}:${API_PORT}"

  worker-service:
    container_name: worker-service
    build:
      context: .
      dockerfile: Dockerfile.worker
    environment:
      - SERVICE_NAME=worker
      - API_TOKEN=${API_TOKEN}
      - REDIS_HOST=redis-db
    restart: always
    labels:
      - autoheal=true
    healthcheck:
      test: ["CMD-SHELL", "[ -n \"$(find /tmp/worker_status -mmin -1)\" ]"]
      interval: 30s
      timeout: 5s
      retries: 3
    depends_on:
      redis-db:
        condition: service_healthy
    volumes:
      - worker_health:/tmp/worker_status

  tg-bot:
    container_name: tg-bot
    build: 
      context: .
      dockerfile: Dockerfile.bot
    environment:
      - SERVICE_NAME=bot
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - API_HOST=weather-api-service
      - API_PORT=${API_PORT}
    depends_on:
      weather-api-service:
        condition: service_started
      worker-service:
        condition: service_started
  autoheal:
    image: willfarrell/autoheal:latest
    container_name: autoheal-monitor
    restart: always
    environment:
      - AUTOHEAL_CONTAINER_LABEL=autoheal
      - AUTOHEAL_INTERVAL=5
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  worker_health:
