services:
  redis-master:
    image: redis:8.8.0-alpine
    container_name: redis-master
    ports:
      - "6379:6379"
    command: redis-server
    networks:
      redis-net:
        ipv4_address: 172.55.0.10
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  redis-replica:
    image: redis:8.8.0-alpine
    container_name: redis-replica
    ports:
      - "6380:6379"
    command: redis-server --replicaof 172.55.0.10 6379
    networks:
      redis-net:
        ipv4_address: 172.55.0.11
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    depends_on:
      redis-master:
        condition: service_healthy

  redis-sentinel-1:
    image: redis:8.8.0-alpine
    container_name: redis-sentinel-1
    ports:
      - "26379:26379"
    command: >
      sh -c "echo 'port 26379' > sentinel.conf &&
             echo 'sentinel resolve-hostnames yes' >> sentinel.conf &&
             echo 'sentinel announce-hostnames yes' >> sentinel.conf &&
             echo 'sentinel monitor mymaster 172.55.0.10 6379 2' >> sentinel.conf &&
             echo 'sentinel down-after-milliseconds mymaster 5000' >> sentinel.conf &&
             echo 'sentinel failover-timeout mymaster 10000' >> sentinel.conf &&
             redis-server sentinel.conf --sentinel"
    restart: unless-stopped
    networks:
      - redis-net
    depends_on:
      redis-master:
        condition: service_healthy

  redis-sentinel-2:
    image: redis:8.8.0-alpine
    container_name: redis-sentinel-2
    ports:
      - "26380:26379"
    command: >
      sh -c "echo 'port 26379' > sentinel.conf &&
             echo 'sentinel resolve-hostnames yes' >> sentinel.conf &&
             echo 'sentinel announce-hostnames yes' >> sentinel.conf &&
             echo 'sentinel monitor mymaster 172.55.0.10 6379 2' >> sentinel.conf &&
             echo 'sentinel down-after-milliseconds mymaster 5000' >> sentinel.conf &&
             echo 'sentinel failover-timeout mymaster 10000' >> sentinel.conf &&
             redis-server sentinel.conf --sentinel"
    restart: unless-stopped
    networks:
      - redis-net
    depends_on:
      redis-master:
        condition: service_healthy

  redis-sentinel-3:
    image: redis:8.8.0-alpine
    container_name: redis-sentinel-3
    ports:
      - "26381:26379"
    command: >
      sh -c "echo 'port 26379' > sentinel.conf &&
             echo 'sentinel resolve-hostnames yes' >> sentinel.conf &&
             echo 'sentinel announce-hostnames yes' >> sentinel.conf &&
             echo 'sentinel monitor mymaster 172.55.0.10 6379 2' >> sentinel.conf &&
             echo 'sentinel down-after-milliseconds mymaster 5000' >> sentinel.conf &&
             echo 'sentinel failover-timeout mymaster 10000' >> sentinel.conf &&
             redis-server sentinel.conf --sentinel"
    restart: unless-stopped
    networks:
      - redis-net
    depends_on:
      redis-master:
        condition: service_healthy
        

  tg-bot:
    container_name: tg-bot
    build: .
    entrypoint: /app/telegram_bot/alembic-entrypoint.sh
    command: ["python", "-m", "telegram_bot.main"]
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - redis-net
    depends_on:
      weather-api:
        condition: service_started
      worker:
        condition: service_started
      postgres-db:
        condition: service_healthy
    volumes:
      - app-logs:/app/logs

  notifications-scheduler:
    container_name: notifications-scheduler
    build: .
    command: python -m telegram_bot.tasks.rq_scheduler
    networks:
      - redis-net
    environment:
      - SERVICE_NAME=notify-scheduler
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - app-logs:/app/logs

  worker-notifier:
    container_name: worker-notifier
    build: .
    command: python -m telegram_bot.tasks.rq_worker
    networks:
      - redis-net
    environment:
      - SERVICE_NAME=worker-notifier
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - app-logs:/app/logs

  weather-api:
    container_name: weather-api
    build: .
    command: ["python", "-m", "weather_api.main"]
    environment:
      - SERVICE_NAME=weather-api
    env_file:
      - .env
    networks:
      - redis-net
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://${API_HOST}:${API_PORT}/health || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
    ports:
      - "${API_PORT}:${API_PORT}"
    depends_on:
      redis-master:
        condition: service_healthy
    volumes:
      - app-logs:/app/logs

  worker:
    container_name: worker
    build: .
    command: ["python", "-m", "worker.main"]
    environment:
      - SERVICE_NAME=worker
    env_file:
      - .env
    networks:
      - redis-net
    restart: unless-stopped
    labels:
      - autoheal=true
    healthcheck:
      test: ["CMD-SHELL", "[ -n \"$(find /tmp/worker_status -mmin -1)\" ]"]
      interval: 30s
      timeout: 5s
      retries: 3
    depends_on:
      redis-master:
        condition: service_healthy
    volumes:
      - app-logs:/app/logs
      - worker_health:/tmp/worker_status


  postgres-db:
    image: postgres:16-alpine
    container_name: postgres-db
    env_file:
      - .env
    networks:
      - redis-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    

  autoheal:
    image: willfarrell/autoheal:latest
    container_name: autoheal-monitor
    restart: unless-stopped
    environment:
      - AUTOHEAL_CONTAINER_LABEL=autoheal
      - AUTOHEAL_INTERVAL=5
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    restart: unless-stopped

  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    volumes:
      - app-logs:/var/log/app
      - ./promtail-config.yaml:/etc/promtail/config.yaml
    command: -config.file=/etc/promtail/config.yaml
    restart: unless-stopped
    depends_on:
      - loki

  grafana:
    image: grafana/grafana:11.0.0
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
    restart: unless-stopped
    depends_on:
      - loki


volumes:
  app-logs:
  worker_health:
  postgres_data:

networks:
  redis-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.55.0.0/16