FROM python:3.12-alpine
ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    PYTHONPATH=/app
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY packages/ ./packages/
COPY telegram_bot/ ./telegram_bot/
COPY .env .
CMD ["python", "telegram_bot/main.py"]
