services:
  redis-limiter:
    image: redis:latest
    container_name: redis-limiter
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
    ports:
      - "${REDIS_LIMITER_PORT}:6379"

  redis-main-storage:
    image: redis:latest
    container_name: redis-main-storage
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
    ports:
      - "${REDIS_WEATHER_PORT}:6379"
  
  redis-backup-storage:
    image: redis:latest
    container_name: redis-backup-storage
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
    ports:
      - "${REDIS_BACKUP_WEATHER_PORT}:6379"

  ollama:
    image: ollama/ollama:latest
    container_name: ollama-service
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama

  weather-api-service:
    container_name: weather-api-service
    build: 
      context: .
      dockerfile: Dockerfile.weather-api
    environment:
      - API_HOST=${API_HOST}
      - API_PORT=${API_PORT}
      - REDIS_LIMITER_PORT=${REDIS_LIMITER_PORT}
      - REDIS_LIMITER_HOST=redis-limiter
      - REDIS_WEATHER_HOST=redis-main-storage
      - REDIS_BACKUP_WEATHER_HOST=redis-backup-storage
    ports:
      - "${API_PORT}:${API_PORT}"

  worker-service:
    container_name: worker-service
    build:
      context: .
      dockerfile: Dockerfile.worker
    environment:
      - API_TOKEN=${API_TOKEN}
      - REDIS_LIMITER_HOST=redis-limiter
      - REDIS_WEATHER_HOST=redis-main-storage
      - REDIS_BACKUP_WEATHER_HOST=redis-backup-storage
    restart: always
    depends_on:
      redis-main-storage:
        condition: service_healthy
      redis-backup-storage:
        condition: service_healthy

  tg-bot:
    container_name: tg-bot
    build: 
      context: .
      dockerfile: Dockerfile.bot
    environment:
      - OLLAMA_HOST=http://ollama:11434
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - API_HOST=weather-api-service
      - API_PORT=${API_PORT}
    depends_on:
      weather-api-service:
        condition: service_started
      worker-service:
        condition: service_started
      ollama:
        condition: service_started

volumes:
  ollama_data: